---
version: 2
plan:
  project-key: EKS
  key: EKS
  name: eks-cluster-spec
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
# Checkout Task will be added implicitly during Specs import
  - script:
      interpreter: SHELL
      scripts:
      - |-
        cd /home/ubuntu/eks/scripts
        wget -q https://s3-us-west-2.amazonaws.com/rafay-prod-cli/publish/rctl-linux-amd64.tar.bz2
        tar -xf rctl-linux-amd64.tar.bz2
        chmod 0755 rctl
        chmod +x rafay_eks_provision.sh
        ./rafay_eks_provision.sh
      environment: RCTL_API_KEY="rafay_api_key", RCTL_API_SECRET="rafay_secret_key", RCTL_REST_ENDPOINT="console.rafay.dev", RCTL_PROJECT="defaultproject"
triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: EKS-EKS
plan-permissions:
- users:
  - ubuntu
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
...

